"use strict";
exports.__esModule = true;
var Moto_1 = require("./Veiculo/Model/Moto");
var Carro_1 = require("./Veiculo/Model/Carro");
var carro = new Carro_1.Carro();
console.log("Meu Carro \n");
carro.acelerar();
carro.desligar();
carro.trocarDeMarcha();
carro.frear();
var moto = new Moto_1.Moto();
console.log("Minha Moto \n");
moto.acelerar();
moto.desligar();
moto.trocarDeMarcha();
moto.frear();
